---
# defaults file for ssh_center

ssh_center:
  host: # must be exactly one line
    - { host: db_agent, user: appd, group: appd, su: root }
  ssh:
    type: rsa
    dir: 
      path: "/home/appd/.ssh"
      mode: "0700"
    private_key: 
      file: "id_rsa"
      path: "/home/appd/.ssh/id_rsa"
      mode: "0600"
    public_key:
      file: "id_rsa.pub"
      path: "/home/appd/.ssh/id_rsa.pub"
      mode: "0644"
    known_hosts: 
      file: "known_hosts"
      path: "/home/appd/.ssh/known_hosts"
      mode: "0644"

ssh_remotes:
  hosts: # can be multiple lines
    - { host: database, user: "{{ secret_dbuser_os_username }}", group: "{{ secret_dbuser_os_group }}", su: root }
