---
tomcat_version: "{{ tomcat_uri_version }}"
tomcat_file_path: "{{ tomcat_uri | basename }}"
tomcat_permissions_production: True
tomcat_users:
  - username: "{{ secret_tomcat_username }}"
    password: "{{ secret_tomcat_password }}"
    roles: "tomcat,admin,manager,manager-gui"
