# ntp and proxy server
secret_ntp_server: "{{ lookup('env','SECRET_LAB_NTP_SERVER') }}" # use your own nts server or use a public server from https://www.pool.ntp.org/zone/nl
secret_http_proxy_host: "{{ lookup('env','SECRET_LAB_HTTP_PROXY') }}" # optional in case of a proxy
secret_http_proxy_port: "{{ lookup('env','SECRET_LAB_HTTP_PORT') }}" # optional in case of a proxy
secret_https_proxy_host: "{{ lookup('env','SECRET_LAB_HTTPS_PROXY') }}" # optional in case of a proxy
secret_https_proxy_port: "{{ lookup('env','SECRET_LAB_HTTPS_PORT') }}" # optional in case of a proxy

# login data for https://download.appdynamics.com/download/
# needed if you want to download and deploy appdynamics
secret_download_username: "{{ lookup('env','SECRET_APPD_USER') }}"
secret_download_password: "{{ lookup('env','SECRET_APPD_PASSWORD') }}"

# database user and pwd for mysql database and jdbc connection string of tomcat server
secret_mysql_username: "supercars"
secret_mysql_password: "supercars"

# tomcat
secret_tomcat_username: "tomcat"
secret_tomcat_password: "{{ lookup('env','SECRET_LAB_PASSWORD') }}"

# DB monitoring users for db and os is used by the appd DB collector
secret_dbuser_username: "DBUSER"
secret_dbuser_password: "{{ lookup('env','SECRET_LAB_PASSWORD') }}"
secret_dbuser_os_username: "dbuser"
secret_dbuser_os_group: "appd"
secret_dbagent_name: "LHINTZSC-SUPERCARS"

# appdynamics agent configuration
secret_controller_url: "{{ lookup('env','SECRET_APPD_CONTROLLER') }}" # account.saas.appdynamics.com
secret_controller_port: '443'
secret_controller_protocoll: 'https'
secret_ssl_enabled: 'true'

secret_account_name: "{{ lookup('env','SECRET_APPD_ACCOUNT') }}" # from account.saas.appdynamics.com -> settings -> license -> account
secret_account_name_global: "{{ lookup('env','SECRET_APPD_ACCOUNT_GLOBAL') }}" # from account.saas.appdynamics.com -> settings -> license -> account
secret_account_key: "{{ lookup('env','SECRET_APPD_ACCOUNT_KEY') }}" # from account.saas.appdynamics.com -> settings -> license -> account

secret_application: 'LHINTZSC-supercars'
secret_tier: 'tomcat'
secret_node: 'computer'

secret_unique_hostid: 'LHINTZSC-{{ ansible_host }}' # take from inventory

secret_sim_enabled: 'true'
secret_metric_path: ""

secret_analytics_agent_name: analytics-agent
secret_analytics_enabled: 'true'

secret_event_custer_url: 'fra-ana-api.saas.appdynamics.com' # saas or on-prem endpoint https://docs.appdynamics.com/display/PAA/SaaS+Domains+and+IP+Ranges
secret_event_custer_port: '443'
secret_event_custer_protocoll: 'https'